# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "bower_components/bootstrap/scss"
  # Paths to JavaScript libraries, which are combined into one file
  javascript:
    # Libraries required by Foundation
    - "bower_components/jquery/dist/jquery.js"
    - "bower_components/moment/moment.js"
    - "bower_components/chart.js/dist/Chart.min.js"
    - "bower_components/select2/dist/js/select2.full.min.js"
    - "bower_components/ckeditor/ckeditor.js"
    - "bower_components/bootstrap-validator/dist/validator.min.js"
    - "bower_components/bootstrap-daterangepicker/daterangepicker.js"
    - "bower_components/dropzone/dist/dropzone.js"
    - "bower_components/editable-table/mindmup-editabletable.js"
    - "bower_components/datatables.net/js/jquery.dataTables.min.js"
    - "bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"
    - "bower_components/fullcalendar/dist/fullcalendar.min.js"
    - "bower_components/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js"
    - "bower_components/tether/dist/js/tether.min.js"
    - "bower_components/bootstrap/js/dist/alert.js"
    - "bower_components/bootstrap/js/dist/util.js"
    - "bower_components/bootstrap/js/dist/button.js"
    - "bower_components/bootstrap/js/dist/carousel.js"
    - "bower_components/bootstrap/js/dist/collapse.js"
    - "bower_components/bootstrap/js/dist/dropdown.js"
    - "bower_components/bootstrap/js/dist/modal.js"
    - "bower_components/bootstrap/js/dist/tab.js"
    - "bower_components/bootstrap/js/dist/tooltip.js"
    - "bower_components/bootstrap/js/dist/popover.js"

  
